export function createSqliteLoanBowStatements(db) {
  const findLoanBowByUsername = db.prepare(`
    SELECT
      username,
      has_loan_bow,
      date_loaned,
      returned_date,
      riser_number,
      limbs_number,
      arrow_count,
      returned_riser,
      returned_limbs,
      returned_arrows,
      quiver,
      returned_quiver,
      finger_tab,
      returned_finger_tab,
      string_item,
      returned_string_item,
      arm_guard,
      returned_arm_guard,
      chest_guard,
      returned_chest_guard,
      sight,
      returned_sight,
      long_rod,
      returned_long_rod,
      pressure_button,
      returned_pressure_button
    FROM member_loan_bows
    WHERE username = ?
  `);

  const upsertLoanBowByUsername = db.prepare(`
    INSERT INTO member_loan_bows (
      username,
      has_loan_bow,
      date_loaned,
      returned_date,
      riser_number,
      limbs_number,
      arrow_count,
      returned_riser,
      returned_limbs,
      returned_arrows,
      quiver,
      returned_quiver,
      finger_tab,
      returned_finger_tab,
      string_item,
      returned_string_item,
      arm_guard,
      returned_arm_guard,
      chest_guard,
      returned_chest_guard,
      sight,
      returned_sight,
      long_rod,
      returned_long_rod,
      pressure_button,
      returned_pressure_button
    )
    VALUES (
      @username,
      @hasLoanBow,
      @dateLoaned,
      @returnedDate,
      @riserNumber,
      @limbsNumber,
      @arrowCount,
      @returnedRiser,
      @returnedLimbs,
      @returnedArrows,
      @quiver,
      @returnedQuiver,
      @fingerTab,
      @returnedFingerTab,
      @stringItem,
      @returnedStringItem,
      @armGuard,
      @returnedArmGuard,
      @chestGuard,
      @returnedChestGuard,
      @sight,
      @returnedSight,
      @longRod,
      @returnedLongRod,
      @pressureButton,
      @returnedPressureButton
    )
    ON CONFLICT(username) DO UPDATE SET
      has_loan_bow = excluded.has_loan_bow,
      date_loaned = excluded.date_loaned,
      returned_date = excluded.returned_date,
      riser_number = excluded.riser_number,
      limbs_number = excluded.limbs_number,
      arrow_count = excluded.arrow_count,
      returned_riser = excluded.returned_riser,
      returned_limbs = excluded.returned_limbs,
      returned_arrows = excluded.returned_arrows,
      quiver = excluded.quiver,
      returned_quiver = excluded.returned_quiver,
      finger_tab = excluded.finger_tab,
      returned_finger_tab = excluded.returned_finger_tab,
      string_item = excluded.string_item,
      returned_string_item = excluded.returned_string_item,
      arm_guard = excluded.arm_guard,
      returned_arm_guard = excluded.returned_arm_guard,
      chest_guard = excluded.chest_guard,
      returned_chest_guard = excluded.returned_chest_guard,
      sight = excluded.sight,
      returned_sight = excluded.returned_sight,
      long_rod = excluded.long_rod,
      returned_long_rod = excluded.returned_long_rod,
      pressure_button = excluded.pressure_button,
      returned_pressure_button = excluded.returned_pressure_button
  `);

  return {
    findLoanBowByUsername,
    upsertLoanBowByUsername,
  };
}
