const seedUsers = [
  {
    username: "CLikley",
    firstName: "Chris",
    surname: "Likley",
    password: "qwe",
    rfidTag: null,
    activeMember: true,
    membershipFeesDue: "2026-12-31",
    coachingVolunteer: true,
    userType: "coach",
    disciplines: ["Recurve Bow"],
  },
  {
    username: "Cfleetham",
    firstName: "Craig",
    surname: "Fleetham",
    password: "abc",
    rfidTag: "7673CF3D",
    activeMember: true,
    membershipFeesDue: "2026-12-31",
    coachingVolunteer: true,
    userType: "developer",
    disciplines: ["Recurve Bow"],
  },
  {
    username: "DStevens",
    firstName: "Kamala",
    surname: "Khan",
    password: "marvel",
    rfidTag: "D9DBCF3D-deactivated",
    activeMember: false,
    membershipFeesDue: "2026-01-01",
    coachingVolunteer: false,
    userType: "general",
    disciplines: ["Recurve Bow"],
  },
  {
    username: "LTaylor",
    firstName: "Les",
    surname: "Taylor",
    password: "123",
    rfidTag: null,
    activeMember: true,
    membershipFeesDue: "2026-12-31",
    coachingVolunteer: true,
    userType: "admin",
    disciplines: [
      "Bare Bow",
      "Compound Bow",
      "Flat Bow",
      "Long Bow",
      "Recurve Bow",
    ],
  },
  {
    username: "MJones",
    firstName: "Jessica",
    surname: "Jones",
    password: "marvel",
    rfidTag: null,
    activeMember: false,
    membershipFeesDue: "2026-04-03",
    coachingVolunteer: false,
    userType: "general",
    disciplines: ["Flat Bow"],
  },
  {
    username: "MMurdock",
    firstName: "Matt",
    surname: "Murdock",
    password: "marvel",
    rfidTag: null,
    activeMember: true,
    membershipFeesDue: "2026-12-31",
    coachingVolunteer: false,
    userType: "general",
    disciplines: ["Bare Bow"],
  },
  {
    username: "NOdinson",
    firstName: "Thor",
    surname: "Odinson",
    password: "marvel",
    rfidTag: null,
    activeMember: true,
    membershipFeesDue: "2026-12-31",
    coachingVolunteer: false,
    userType: "general",
    disciplines: ["Long Bow"],
  },
  {
    username: "PParker",
    firstName: "Peter",
    surname: "Parker",
    password: "marvel",
    rfidTag: null,
    activeMember: true,
    membershipFeesDue: "2026-05-08",
    coachingVolunteer: false,
    userType: "general",
    disciplines: ["Bare Bow", "Recurve Bow"],
  },
  {
    username: "RWilliams",
    firstName: "Riri",
    surname: "Williams",
    password: "marvel",
    rfidTag: null,
    activeMember: true,
    membershipFeesDue: "2026-12-31",
    coachingVolunteer: false,
    userType: "general",
    disciplines: ["Recurve Bow", "Compound Bow"],
  },
  {
    username: "SMaximoff",
    firstName: "Wanda",
    surname: "Maximoff",
    password: "marvel",
    rfidTag: null,
    activeMember: true,
    membershipFeesDue: "2026-12-31",
    userType: "general",
    disciplines: ["Recurve Bow"],
  },
  {
    username: "TBarnes",
    firstName: "Bucky",
    surname: "Barnes",
    password: "marvel",
    rfidTag: null,
    activeMember: true,
    membershipFeesDue: "2026-12-31",
    userType: "general",
    disciplines: ["Compound Bow"],
  },
  {
    username: "TProfile",
    firstName: "Temp",
    surname: "ProfileUpdated",
    password: "tmp",
    rfidTag: "RFID-TPROFILE-001",
    activeMember: true,
    membershipFeesDue: "2026-04-17",
    userType: "coach",
    disciplines: ["Bare Bow", "Recurve Bow"],
  },
];

function toSeedUserRecord(user, hashPassword) {
  return {
    ...user,
    password: hashPassword(user.password),
  };
}

export function getSeedUsers({ hashPassword, isLive }) {
  const selectedUsers = isLive
    ? seedUsers.filter((user) => user.username === "Cfleetham")
    : seedUsers;

  return selectedUsers.map((user) => toSeedUserRecord(user, hashPassword));
}

