import {
  ARROW_COLOUR_OPTIONS,
  ARROW_COLOUR_VALUE_SET,
  ARROW_FLETCHING_COLOUR_OPTIONS,
  ARROW_FLETCHING_COLOUR_VALUE_SET,
  ARROW_MATERIAL_OPTIONS,
  ARROW_MATERIAL_OPTION_SET,
  ARROW_NOCK_COLOUR_OPTIONS,
  ARROW_NOCK_COLOUR_VALUE_SET,
} from "./arrowSchema.js";

export const LOST_ARROW_ARROW_MATERIAL_OPTIONS = ARROW_MATERIAL_OPTIONS;

export const LOST_ARROW_TARGET_DISTANCE_OPTIONS = [
  "10yrds",
  "15yrds",
  "20yrds",
  "30yrds",
  "40yrds",
  "50yrds",
  "60yrds",
  "70mtr",
  "80yrds",
  "90yrds",
  "100yrds",
];

export const LOST_ARROW_ARROW_COLOUR_OPTIONS = ARROW_COLOUR_OPTIONS;

export const LOST_ARROW_FLETCHING_COLOUR_OPTIONS = ARROW_FLETCHING_COLOUR_OPTIONS;

export const LOST_ARROW_NOCK_COLOUR_OPTIONS = ARROW_NOCK_COLOUR_OPTIONS;

export const LOST_ARROW_ARROW_MATERIAL_OPTION_SET = ARROW_MATERIAL_OPTION_SET;
export const LOST_ARROW_TARGET_DISTANCE_OPTION_SET = new Set(
  LOST_ARROW_TARGET_DISTANCE_OPTIONS,
);
export const LOST_ARROW_ARROW_COLOUR_VALUE_SET = ARROW_COLOUR_VALUE_SET;
export const LOST_ARROW_FLETCHING_COLOUR_VALUE_SET = ARROW_FLETCHING_COLOUR_VALUE_SET;
export const LOST_ARROW_NOCK_COLOUR_VALUE_SET = ARROW_NOCK_COLOUR_VALUE_SET;
